import { ProviderManifest, ModelStatus } from '../../types.js';
import { defaultKokoroConfig } from './config.js';

/** Kokoro provider manifest */
export const kokoroManifest: ProviderManifest = {
  id: 'kokoro',
  name: 'Kokoro',
  type: 'tts',
  version: '1.0.0',
  description: 'Lightweight high-quality TTS model',
  author: 'Kokoro Team',
  license: 'MIT',
  supportedLanguages: defaultKokoroConfig.languages,
  models: [
    {
      id: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Kokoro 82M',
      version: '1.0.0',
      size: 165000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/kokoro-team/kokoro-82M/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: ['en', 'en-gb'],
      capabilities: ['tts'],
      minProviderVersion: '1.0.0',
    },
  ],
  voices: [
    // American Female
    {
      id: 'af_bella',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Bella (AF)',
      language: 'en',
      gender: 'female',
      description: 'Warm American female voice',
      sampleRate: 24000,
      isDefault: true,
    },
    {
      id: 'af_sarah',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Sarah (AF)',
      language: 'en',
      gender: 'female',
      description: 'Clear American female voice',
      sampleRate: 24000,
      isDefault: false,
    },
    {
      id: 'af_sky',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Sky (AF)',
      language: 'en',
      gender: 'female',
      description: 'Bright American female voice',
      sampleRate: 24000,
      isDefault: false,
    },
    {
      id: 'af_nicole',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Nicole (AF)',
      language: 'en',
      gender: 'female',
      description: 'Expressive American female voice',
      sampleRate: 24000,
      isDefault: false,
    },
    // American Male
    {
      id: 'am_adam',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Adam (AM)',
      language: 'en',
      gender: 'male',
      description: 'Clear American male voice',
      sampleRate: 24000,
      isDefault: false,
    },
    {
      id: 'am_michael',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Michael (AM)',
      language: 'en',
      gender: 'male',
      description: 'Deep American male voice',
      sampleRate: 24000,
      isDefault: false,
    },
    // British Female
    {
      id: 'bf_emma',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Emma (BF)',
      language: 'en-gb',
      gender: 'female',
      description: 'Elegant British female voice',
      sampleRate: 24000,
      isDefault: false,
    },
    {
      id: 'bf_isabella',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Isabella (BF)',
      language: 'en-gb',
      gender: 'female',
      description: 'Refined British female voice',
      sampleRate: 24000,
      isDefault: false,
    },
    // British Male
    {
      id: 'bm_george',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'George (BM)',
      language: 'en-gb',
      gender: 'male',
      description: 'Rich British male voice',
      sampleRate: 24000,
      isDefault: false,
    },
    {
      id: 'bm_lewis',
      modelId: 'kokoro-82M',
      providerId: 'kokoro',
      name: 'Lewis (BM)',
      language: 'en-gb',
      gender: 'male',
      description: 'Crisp British male voice',
      sampleRate: 24000,
      isDefault: false,
    },
  ],
};

/** Gets the Kokoro manifest */
export function getKokoroManifest(): ProviderManifest {
  return JSON.parse(JSON.stringify(kokoroManifest));
}