import { ProviderManifest, ModelStatus } from '../../types.js';
import { defaultPiperConfig } from './config.js';

/** Piper provider manifest */
export const piperManifest: ProviderManifest = {
  id: 'piper',
  name: 'Piper',
  type: 'tts',
  version: '1.0.0',
  description: 'Fast local neural TTS',
  author: 'Rhasspy',
  license: 'MIT',
  supportedLanguages: defaultPiperConfig.languages,
  models: [
    {
      id: 'piper-en',
      providerId: 'piper',
      name: 'Piper English',
      version: '1.0.0',
      size: 50000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium.onnx',
      status: ModelStatus.AVAILABLE,
      languages: ['en'],
      capabilities: ['tts'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'piper-en-gb',
      providerId: 'piper',
      name: 'Piper English (GB)',
      version: '1.0.0',
      size: 50000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium.onnx',
      status: ModelStatus.AVAILABLE,
      languages: ['en-gb'],
      capabilities: ['tts'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'piper-de',
      providerId: 'piper',
      name: 'Piper German',
      version: '1.0.0',
      size: 50000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/medium.onnx',
      status: ModelStatus.AVAILABLE,
      languages: ['de'],
      capabilities: ['tts'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'piper-fr',
      providerId: 'piper',
      name: 'Piper French',
      version: '1.0.0',
      size: 50000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium.onnx',
      status: ModelStatus.AVAILABLE,
      languages: ['fr'],
      capabilities: ['tts'],
      minProviderVersion: '1.0.0',
    },
  ],
  voices: [
    // English US
    {
      id: 'en_US-lessac',
      modelId: 'piper-en',
      providerId: 'piper',
      name: 'Lessac (US Female)',
      language: 'en',
      gender: 'female',
      description: 'American English female voice',
      sampleRate: 22050,
      isDefault: true,
    },
    {
      id: 'en_US-ryan',
      modelId: 'piper-en',
      providerId: 'piper',
      name: 'Ryan (US Male)',
      language: 'en',
      gender: 'male',
      description: 'American English male voice',
      sampleRate: 22050,
      isDefault: false,
    },
    {
      id: 'en_US-amy',
      modelId: 'piper-en',
      providerId: 'piper',
      name: 'Amy (US Female)',
      language: 'en',
      gender: 'female',
      description: 'Warm American English female voice',
      sampleRate: 22050,
      isDefault: false,
    },
    {
      id: 'en_US-kusal',
      modelId: 'piper-en',
      providerId: 'piper',
      name: 'Kusal (US Male)',
      language: 'en',
      gender: 'male',
      description: 'Deep American English male voice',
      sampleRate: 22050,
      isDefault: false,
    },
    // English GB
    {
      id: 'en_GB-alan',
      modelId: 'piper-en-gb',
      providerId: 'piper',
      name: 'Alan (GB Male)',
      language: 'en-gb',
      gender: 'male',
      description: 'British English male voice',
      sampleRate: 22050,
      isDefault: false,
    },
    {
      id: 'en_GB-jenny',
      modelId: 'piper-en-gb',
      providerId: 'piper',
      name: 'Jenny (GB Female)',
      language: 'en-gb',
      gender: 'female',
      description: 'British English female voice',
      sampleRate: 22050,
      isDefault: false,
    },
    // German
    {
      id: 'de_DE-thorsten',
      modelId: 'piper-de',
      providerId: 'piper',
      name: 'Thorsten (DE Male)',
      language: 'de',
      gender: 'male',
      description: 'German male voice',
      sampleRate: 22050,
      isDefault: false,
    },
    // French
    {
      id: 'fr_FR-siwis',
      modelId: 'piper-fr',
      providerId: 'piper',
      name: 'Siwis (FR Female)',
      language: 'fr',
      gender: 'female',
      description: 'French female voice',
      sampleRate: 22050,
      isDefault: false,
    },
  ],
};

/** Gets the Piper manifest */
export function getPiperManifest(): ProviderManifest {
  return JSON.parse(JSON.stringify(piperManifest));
}