// ─────────────────────────────────────────────────────────────────────────────
// forge/agentLoop.ts
//
// One iteration of THINK -> ACT -> EVALUATE -> CHECKPOINT. The orchestrator's
// drive loop calls this repeatedly; each call is fully self-contained and
// reloads all state fresh from the DB — never from a prior iteration's
// memory — so a crash between any two iterations loses nothing.
//
// The entire body is wrapped in try/catch: an uncaught exception marks the
// current task blocked and returns 'continued' — never an unhandled crash
// that takes down the whole overnight run (same fail-safe shape as
// services/cluster.ts's executeClusterTool).
// ─────────────────────────────────────────────────────────────────────────────

import * as db from "./db";
import * as taskTree from "./taskTree";
import * as execWorker from "./execWorker";
import * as contracts from "./contracts";
import { callForgeModel, extractJson, ForgeModelError } from "./modelClient";
import { buildThinkPrompt } from "./prompts/think";
import { buildEvaluatePrompt } from "./prompts/evaluate";
import { buildIntegrationCheckPrompt } from "./prompts/integrationCheck";
import { getStackProfile } from "./stacks/registry";
import {
    DEFAULT_COMMAND_TIMEOUT_MS,
    INSTALL_COMMAND_TIMEOUT_MS,
} from "./constants";
import type { AgentAction, EvaluationResult, TaskNode } from "./types";

export type IterationResult = "continued" | "session_done" | "session_blocked";

// Mandatory, unconditional — called whenever a session reaches ANY terminal
// state (done or blocked), regardless of whether the model's own review-pass
// task actually wrote one. The stack profile's scaffold instructs the model
// to write a real README, but nothing forces it to succeed — this is the
// guarantee, not a hope. If README.md already exists, this is a no-op.
async function ensureReadmeExists(sessionId: string): Promise<void> {
    try {
        await execWorker.readFile(sessionId, "README.md");
        return; // already exists, nothing to do
    } catch {
        // Doesn't exist — fall through and write a basic one.
    }

    try {
        const session = await db.getSession(sessionId);
        if (!session) return;
        const profile = getStackProfile(session.stackProfileId);
        const tree = await db.getTaskTree(sessionId);

        const content =
            `# ${session.goal}\n\n` +
            `Stack: ${session.stackProfileId}${session.customStack ? ` (${session.customStack})` : ""}\n\n` +
            `## Install\n\n` +
            "```bash\n" +
            `${profile.packageManager === "npm" ? "npm install" : profile.packageManager === "pip" ? "pip install -r requirements.txt" : profile.packageManager === "maven" ? "mvn install" : "# see project files for this stack's install command"}\n` +
            "```\n\n" +
            `## Run\n\n` +
            "```bash\n" +
            `${profile.runCmd.replace(/\{\{PORT\}\}/g, String(session.allocatedPort))}\n` +
            "```\n\n" +
            `## Test\n\n` +
            "```bash\n" +
            `${profile.testCmd}\n` +
            "```\n\n" +
            `## Build log\n\n` +
            tree.map((t) => `- [${t.status === "done" ? "x" : " "}] ${t.description}`).join("\n") +
            "\n\n_This README was auto-generated by Forge because the build's own " +
            "review-pass task did not produce one — see todo.md for full task " +
            "status and SETUP.md (if present) for any last-mile setup notes._\n";

        await execWorker.writeFile(sessionId, "README.md", content);
        console.log(`[FORGE][LOOP] wrote fallback README.md for session ${sessionId}`);
    } catch (err) {
        console.error("[FORGE][LOOP] failed to write fallback README.md:", err);
    }
}

// Called only when the task going 'blocked' is the mandatory integration
// check — i.e. every file has already been written (that's every task
// BEFORE this one in the dependency chain), but the automated server-start
// smoke test itself failed (port conflict, missing system dependency,
// uncaught runtime error, etc). Rather than leave the session as a dead end
// with nothing but an error string, write a real SETUP.md into the
// workspace: what was attempted, what failed, and what a human should try
// manually. The code is real and complete at this point — this file is
// about the LAST MILE (running it), not about redoing any of the work.
async function generateSetupReadme(
    sessionId: string,
    task: TaskNode,
    reason: string
): Promise<void> {
    try {
        const session = await db.getSession(sessionId);
        if (!session) return;
        const profile = getStackProfile(session.stackProfileId);

        const content =
            `# Setup Required\n\n` +
            `Forge finished writing every file for this project, but the final ` +
            `automated integration check could not confirm the server actually ` +
            `starts and responds. **This does not mean the code is broken** — it ` +
            `means the automated check couldn't verify it in this environment. ` +
            `Most commonly this is a port already in use, a missing system-level ` +
            `dependency, or an environment difference between the sandbox and ` +
            `your machine.\n\n` +
            `## What the integration check tried\n\n` +
            "```\n" + task.description + "\n```\n\n" +
            `## What it reported\n\n` +
            "```\n" + reason + "\n```\n\n" +
            `## Try running it yourself\n\n` +
            "```bash\n" +
            `${profile.packageManager === "npm" ? "npm install" : profile.packageManager === "pip" ? "pip install -r requirements.txt" : "# install dependencies for this stack"}\n` +
            `${profile.runCmd.replace(/\{\{PORT\}\}/g, String(session.allocatedPort))}\n` +
            "```\n\n" +
            `If it still doesn't start, the error message from that command directly ` +
            `will be far more specific than what the automated check captured — start ` +
            `there. Common things to check: is the port above already in use by ` +
            `something else, are all dependencies actually installed, and does your ` +
            `local environment have the same runtime version this was built against.\n`;

        await execWorker.writeFile(sessionId, "SETUP.md", content);
        console.log(`[FORGE][LOOP] wrote SETUP.md for session ${sessionId} after integration check failure`);
    } catch (err) {
        // Never let README generation itself throw and mask the real
        // blocked-task error — this is a best-effort convenience, not
        // load-bearing.
        console.error("[FORGE][LOOP] failed to write SETUP.md:", err);
    }
}

// Parses and validates the THINK response into an AgentAction. Rejects an
// empty reasoning string outright — never allowed to pass silently.
function parseAgentAction(raw: string): AgentAction {
    const parsed = extractJson<any>(raw);

    if (Array.isArray(parsed)) {
        throw new ForgeModelError(
            "THINK returned an array of actions — exactly one action is required"
        );
    }
    if (typeof parsed?.reasoning !== "string" || !parsed.reasoning.trim()) {
        throw new ForgeModelError("THINK action has empty/missing 'reasoning'");
    }

    switch (parsed.type) {
        case "write_file":
            if (typeof parsed.path !== "string" || typeof parsed.content !== "string") {
                throw new ForgeModelError("write_file action missing path/content");
            }
            // contract is optional. If the model attempted one but got the
            // shape wrong, DO NOT throw — that would crash an otherwise
            // perfectly valid write_file action over a bonus field that
            // failed. Smaller models (this was caught running gemma3:4b)
            // reliably struggle with nested-object sub-fields specifically;
            // punishing the whole action for that is disproportionate. Strip
            // the malformed contract, log it clearly so it's visible in the
            // live tail, and let the file write proceed normally. The
            // contract-injection mechanism simply won't have this one
            // available to dependent tasks — worse than a perfect contract,
            // better than blocking the task entirely.
            if (parsed.contract !== undefined) {
                const c = parsed.contract;
                const wellFormed =
                    typeof c === "object" &&
                    c !== null &&
                    typeof c.name === "string" &&
                    c.name.trim() &&
                    typeof c.definition === "string" &&
                    c.definition.trim();
                if (!wellFormed) {
                    console.warn(
                        "[FORGE][LOOP] dropped malformed 'contract' on write_file " +
                            `(path=${parsed.path}); proceeding without it. Raw value:`,
                        JSON.stringify(c)
                    );
                    delete parsed.contract;
                }
            }
            return parsed;
        case "read_file":
        case "delete_file":
        case "list_dir":
            if (typeof parsed.path !== "string") {
                throw new ForgeModelError(`${parsed.type} action missing path`);
            }
            return parsed;
        case "run_command":
            if (typeof parsed.cmd !== "string" || !parsed.cmd.trim()) {
                throw new ForgeModelError("run_command action missing cmd");
            }
            return parsed;
        default:
            throw new ForgeModelError(
                `Unknown action type: ${String(parsed?.type)}`
            );
    }
}

function parseEvaluation(raw: string): EvaluationResult {
    const parsed = extractJson<any>(raw);
    if (typeof parsed?.reasoning !== "string" || !parsed.reasoning.trim()) {
        throw new ForgeModelError("EVALUATE result has empty/missing 'reasoning'");
    }
    if (!["pass", "retry", "blocked"].includes(parsed?.verdict)) {
        throw new ForgeModelError(
            `EVALUATE verdict invalid: ${String(parsed?.verdict)}`
        );
    }
    return { reasoning: parsed.reasoning, verdict: parsed.verdict };
}

// Package-manager installs get the long timeout automatically — the model
// often forgets to ask for one, and a timed-out npm install poisons the
// workspace with a half-written node_modules.
function timeoutForCommand(action: Extract<AgentAction, { type: "run_command" }>): number {
    if (typeof action.timeoutMs === "number" && action.timeoutMs > 0) {
        return Math.min(action.timeoutMs, INSTALL_COMMAND_TIMEOUT_MS);
    }
    const installish = /\b(npm|pnpm|yarn|pip|pip3|mvn|gradle|cargo)\b.*\b(install|ci|add|package|dependency)\b|\bnpm ci\b|\bpip install\b/i;
    return installish.test(action.cmd)
        ? INSTALL_COMMAND_TIMEOUT_MS
        : DEFAULT_COMMAND_TIMEOUT_MS;
}

// Dispatches the chosen action through execWorker (which logs the ACT phase
// itself) and returns a textual observation for EVALUATE.
async function dispatchAction(
    sessionId: string,
    task: TaskNode,
    action: AgentAction
): Promise<string> {
    switch (action.type) {
        case "write_file": {
            await execWorker.writeFile(sessionId, action.path, action.content);

            // If this write also declared a contract, register it NOW — same
            // turn as the file that defines it. Namespaced to this task via
            // contractKeyForTask so getContractsForTask's ancestry walk scopes
            // it correctly to dependents, not session-globally.
            if (action.contract) {
                const session = await db.getSession(sessionId);
                if (session) {
                    const key = contracts.contractKeyForTask(
                        task.id,
                        action.contract.name
                    );
                    await contracts.registerContract(
                        session,
                        key,
                        action.contract.definition
                    );
                    console.log(
                        `[FORGE][LOOP] contract registered: ${action.contract.name} (task ${task.id})`
                    );
                }
            }

            // CRITICAL: the observation must include the ACTUAL content
            // written, not just a byte count. This was the real root cause of
            // EVALUATE repeatedly misjudging genuinely-correct short files
            // (e.g. a valid 28-character requirements.txt) as "placeholder"
            // or "incomplete" — it was never shown what was actually written,
            // only told how many characters, and had to guess/hallucinate
            // whether that content was right. A judge cannot judge evidence
            // it was never given. Truncate only for genuinely large files, so
            // the EVALUATE prompt for a normal-sized source file stays
            // bounded without starving it of the one thing it needs to judge
            // correctly.
            const MAX_OBSERVED_CONTENT_CHARS = 4000;
            const shown =
                action.content.length > MAX_OBSERVED_CONTENT_CHARS
                    ? action.content.slice(0, MAX_OBSERVED_CONTENT_CHARS) +
                      `\n... [truncated, ${action.content.length} total chars]`
                    : action.content;

            return (
                `write_file OK: wrote ${action.content.length} chars to ${action.path}` +
                (action.contract ? ` (registered contract: ${action.contract.name})` : "") +
                `\n--- content of ${action.path} ---\n${shown}\n--- end content ---`
            );
        }
        case "read_file": {
            const content = await execWorker.readFile(sessionId, action.path);
            return `read_file OK: ${action.path}\n${content}`;
        }
        case "delete_file": {
            await execWorker.deleteFile(sessionId, action.path);
            return `delete_file OK: ${action.path}`;
        }
        case "list_dir": {
            const entries = await execWorker.listDir(sessionId, action.path);
            return `list_dir OK: ${action.path}\n${entries.join("\n")}`;
        }
        case "run_command": {
            if (!task.isIntegrationCheck) {
                // HARD ENFORCEMENT, not just a prompt request: run_command is
                // structurally refused for every task except the mandatory
                // integration check. This is the actual backstop for models
                // that ignore the "don't run commands mid-build" instruction
                // in prompts/think.ts — the command never reaches
                // execWorker.runCommand at all, so it cannot execute
                // regardless of what the model decided. Returned as a normal
                // observation (not a thrown error) so EVALUATE sees it and
                // the loop naturally retries with a corrected action, rather
                // than crashing the iteration.
                console.warn(
                    `[FORGE][LOOP] blocked run_command on non-integration-check task ` +
                        `${task.id}: "${action.cmd}" — command execution is only allowed ` +
                        `in the mandatory final integration check`
                );
                return (
                    `REJECTED: run_command is not allowed for this task. This is a ` +
                    `regular content task — write or fix file content instead. All ` +
                    `command execution (install, compile, test, server-start) happens ` +
                    `exactly once, later, in a separate mandatory final task. The ` +
                    `command "${action.cmd}" was NOT executed.`
                );
            }
            const result = await execWorker.runCommand(
                sessionId,
                action.cmd,
                timeoutForCommand(action)
            );
            return [
                `run_command: ${action.cmd}`,
                `exit code: ${result.exitCode}${result.timedOut ? " (TIMED OUT)" : ""}`,
                `stdout:\n${result.stdout.slice(-8000)}`,
                `stderr:\n${result.stderr.slice(-8000)}`,
            ].join("\n");
        }
    }
}

// Recently-touched files for THINK context — re-read FRESH from disk every
// iteration via execWorker.readFile paths logged in prior ACTs. Never trusts
// a prior iteration's in-memory copy.
async function loadRelevantFiles(
    sessionId: string,
    task: TaskNode
): Promise<Record<string, string>> {
    const iterations = await db.getIterationsForTask(task.id, "act", 20);
    const paths = new Set<string>();

    for (const it of iterations) {
        try {
            const input = JSON.parse(it.input);
            if (
                (input.type === "write_file" || input.type === "read_file") &&
                typeof input.path === "string"
            ) {
                paths.add(input.path);
            }
        } catch {
            continue;
        }
    }

    const files: Record<string, string> = {};
    for (const p of [...paths].slice(0, 8)) {
        try {
            files[p] = (await execWorker.readFile(sessionId, p)).slice(0, 12_000);
        } catch {
            // File may have been deleted since — skip, don't crash the THINK.
        }
    }
    return files;
}

// Writes a human-readable todo.md into the workspace root mirroring the
// current task tree — checked-off completed tasks, current task marked, rest
// pending. This is a REAL file the agent (and you) can open directly, not
// just internal DB state — the point is contextual continuity: every THINK
// prompt already re-reads relevant source files fresh (never trusting
// memory), and now it can do the same for "what is the overall plan and
// where are we in it" by reading this file rather than re-deriving it. Kept
// deliberately simple (checkbox list, not prose) so it stays cheap to
// regenerate and cheap for the model to skim.
export async function writeTodoFile(sessionId: string): Promise<void> {
    try {
        const tree = await db.getTaskTree(sessionId);
        const session = await db.getSession(sessionId);
        if (!session) return;

        const lines: string[] = [
            `# TODO — ${session.goal}`,
            "",
            `Stack: ${session.stackProfileId} | Status: ${session.status}`,
            "",
        ];

        for (const t of tree) {
            const box =
                t.status === "done"
                    ? "[x]"
                    : t.status === "in_progress"
                      ? "[~]"
                      : t.status === "blocked" || t.status === "failed"
                        ? "[!]"
                        : "[ ]";
            const marker = t.isIntegrationCheck ? " (final integration check)" : "";
            lines.push(`- ${box} ${t.description}${marker}`);
            if (t.status === "blocked" && t.lastError) {
                lines.push(`      blocked: ${t.lastError.slice(0, 200)}`);
            }
        }

        lines.push("");
        lines.push(
            "_This file is regenerated automatically by Forge as tasks complete — " +
                "edits here are not read back into the plan._"
        );

        await execWorker.writeFile(sessionId, "todo.md", lines.join("\n"));
    } catch (err) {
        // Best-effort — never let todo.md generation block or crash a real
        // iteration over a convenience file.
        console.error("[FORGE][LOOP] failed to write todo.md:", err);
    }
}

export async function runIteration(
    sessionId: string
): Promise<IterationResult> {
    let task: TaskNode | null = null;

    try {
        // 1. Load session + contracts FRESH from the DB (never cached).
        const session = await db.getSession(sessionId);
        if (!session) {
            console.error("[FORGE][LOOP] session not found:", sessionId);
            return "session_blocked";
        }

        // 2. Pick the next actionable task; null means everything (including
        //    the mandatory integration check) is done OR unresolvable.
        task = await taskTree.pickNextTask(sessionId);
        if (!task) {
            const tree = await db.getTaskTree(sessionId);

            // A 'failed' integration check is NOT a session failure — it's
            // the intentional skip-after-a-couple-of-tries outcome (see
            // taskTree.markStuckAndContinue): every real content task
            // already passed, only the final server-start smoke test
            // couldn't be verified. That's "done, with a note in
            // SETUP.md," not "blocked." Any OTHER task being blocked/failed
            // (a real content task never got finished) is a genuine block.
            const anyRegularTaskBlocked = tree.some(
                (t) =>
                    !t.isIntegrationCheck &&
                    (t.status === "blocked" || t.status === "failed")
            );

            await db.updateSessionStatus(
                sessionId,
                anyRegularTaskBlocked ? "blocked" : "done"
            );
            console.log(
                `[FORGE][LOOP] session ${sessionId} ${anyRegularTaskBlocked ? "blocked" : "done"}`
            );
            // Mandatory regardless of how the session ended — never trust
            // the model's own review-pass task to have succeeded at this.
            await ensureReadmeExists(sessionId);
            return anyRegularTaskBlocked ? "session_blocked" : "session_done";
        }

        if (task.status === "pending") {
            await db.updateTaskStatus(task.id, "in_progress");
        }
        execWorker.setActiveTask(sessionId, task.id);

        // 3. Fresh file contents relevant to the task.
        const relevantFiles = await loadRelevantFiles(sessionId, task);

        // 4. Contracts from the task's dependency ancestry — required input
        //    to buildThinkPrompt by construction.
        const taskContracts = await contracts.getContractsForTask(session, task);

        // 5. THINK.
        const stackProfile = getStackProfile(session.stackProfileId);
        const thinkPrompt = task.isIntegrationCheck
            ? buildIntegrationCheckPrompt(session, stackProfile) +
              "\n\n" +
              buildThinkPrompt(task, relevantFiles, taskContracts, task.lastError ?? undefined)
            : buildThinkPrompt(task, relevantFiles, taskContracts, task.lastError ?? undefined);

        const thinkRaw = await callForgeModel(thinkPrompt, { modelId: session.modelId, sessionId });
        const action = parseAgentAction(thinkRaw);
        console.log(`[FORGE][LOOP] THINK -> ${action.type}: ${action.reasoning}`);

        // 10a. Checkpoint the THINK phase unconditionally (ACT is logged
        //      inside execWorker itself).
        await db.logIteration(
            sessionId,
            task.id,
            "think",
            thinkPrompt,
            JSON.stringify(action)
        );

        // 6 + 7. ACT and capture the observation.
        let observation: string;
        try {
            observation = await dispatchAction(sessionId, task, action);
        } catch (err) {
            // Guard violations and fs errors are observations too — the
            // EVALUATE call decides retry vs blocked from them.
            observation = `ACTION FAILED: ${String(err)}`;
            console.warn("[FORGE][LOOP] action failed:", String(err));
        }

        // 8. EVALUATE — always a separate model call from THINK.
        const evaluatePrompt = buildEvaluatePrompt(task, observation);
        const evaluateRaw = await callForgeModel(evaluatePrompt, { modelId: session.modelId, sessionId });
        const evaluation = parseEvaluation(evaluateRaw);
        console.log(
            `[FORGE][LOOP] EVALUATE -> ${evaluation.verdict}: ${evaluation.reasoning}`
        );

        // 10b. Checkpoint the EVALUATE phase unconditionally.
        await db.logIteration(
            sessionId,
            task.id,
            "evaluate",
            evaluatePrompt,
            JSON.stringify(evaluation)
        );

        await db.incrementSessionIterationCount(sessionId);

        // 9. Apply the verdict.
        if (evaluation.verdict === "pass") {
            await db.updateTaskStatus(task.id, "done");
        } else if (evaluation.verdict === "retry") {
            await db.updateTaskStatus(task.id, "in_progress", evaluation.reasoning);
            await db.incrementTaskAttempts(task.id);
            const fresh = await db.getTask(task.id);
            if (fresh && (await taskTree.checkStuck(fresh))) {
                await taskTree.markStuckAndContinue(fresh);
                if (fresh.isIntegrationCheck) {
                    await generateSetupReadme(sessionId, fresh, evaluation.reasoning);
                }
            }
        } else {
            // blocked — same path as stuck, immediately.
            await db.updateTaskStatus(task.id, "blocked", evaluation.reasoning);
            const fresh = await db.getTask(task.id);
            if (fresh) {
                await taskTree.markStuckAndContinue(fresh);
                if (fresh.isIntegrationCheck) {
                    await generateSetupReadme(sessionId, fresh, evaluation.reasoning);
                }
            }
        }

        // Keep todo.md current — the model's next THINK call, and you, both
        // see accurate live state instead of a stale snapshot.
        await writeTodoFile(sessionId);

        return "continued";
    } catch (err) {
        // The overnight-run guarantee: any uncaught exception blocks the
        // current task and CONTINUES — never crashes the drive loop.
        console.error("[FORGE][LOOP] iteration crashed:", err);
        if (task) {
            try {
                await db.updateTaskStatus(task.id, "blocked", String(err));
                const fresh = await db.getTask(task.id);
                if (fresh) {
                    await taskTree.markStuckAndContinue(fresh);
                    if (fresh.isIntegrationCheck) {
                        await generateSetupReadme(sessionId, fresh, String(err));
                    }
                }
            } catch (dbErr) {
                console.error("[FORGE][LOOP] failed to mark task blocked:", dbErr);
            }
        }
        return "continued";
    }
}