import { ProviderManifest, ModelStatus } from '../../types.js';
import { defaultWhisperConfig } from './config.js';

/** Whisper provider manifest */
export const whisperManifest: ProviderManifest = {
  id: 'whisper',
  name: 'Whisper',
  type: 'stt',
  version: '1.0.0',
  description: 'OpenAI Whisper speech recognition',
  author: 'OpenAI',
  license: 'MIT',
  supportedLanguages: defaultWhisperConfig.languages,
  models: [
    {
      id: 'whisper-tiny',
      providerId: 'whisper',
      name: 'Whisper Tiny',
      version: '1.0.0',
      size: 75000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/openai/whisper-tiny/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: defaultWhisperConfig.languages,
      capabilities: ['stt'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'whisper-base',
      providerId: 'whisper',
      name: 'Whisper Base',
      version: '1.0.0',
      size: 150000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/openai/whisper-base/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: defaultWhisperConfig.languages,
      capabilities: ['stt'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'whisper-small',
      providerId: 'whisper',
      name: 'Whisper Small',
      version: '1.0.0',
      size: 465000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/openai/whisper-small/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: defaultWhisperConfig.languages,
      capabilities: ['stt'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'whisper-medium',
      providerId: 'whisper',
      name: 'Whisper Medium',
      version: '1.0.0',
      size: 1420000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/openai/whisper-medium/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: defaultWhisperConfig.languages,
      capabilities: ['stt'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'whisper-large-v3',
      providerId: 'whisper',
      name: 'Whisper Large v3',
      version: '3.0.0',
      size: 2880000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/openai/whisper-large-v3/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: defaultWhisperConfig.languages,
      capabilities: ['stt'],
      minProviderVersion: '1.0.0',
    },
    {
      id: 'whisper-large-v3-turbo',
      providerId: 'whisper',
      name: 'Whisper Large v3 Turbo',
      version: '3.0.0',
      size: 1540000000,
      checksum: '',
      checksumAlgorithm: 'sha256',
      downloadUrl: 'https://huggingface.co/openai/whisper-large-v3-turbo/resolve/main/model.bin',
      status: ModelStatus.AVAILABLE,
      languages: defaultWhisperConfig.languages,
      capabilities: ['stt'],
      minProviderVersion: '1.0.0',
    },
  ],
  voices: [],
};

/** Gets the Whisper manifest */
export function getWhisperManifest(): ProviderManifest {
  return JSON.parse(JSON.stringify(whisperManifest));
}